spring:
  datasource:
    url: jdbc:mysql://db-toucheese-1.cja2kuiisy1n.ap-northeast-2.rds.amazonaws.com/toucheese_db
    username: root
    password: ${secret.prod-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  request-url: ${secret.prod-request-url}